version: "3.8"
name: sieutoc-platform

services:
  postgres:
    container_name: sieutoc-platform-postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready --dbname=${POSTGRES_DB} --username=${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    container_name: sieutoc-platform-redis
    image: redis:7-alpine
    ports:
      - "6380:6379"

  mailpit:
    container_name: sieutoc-platform-mailpit
    image: axllent/mailpit:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  data:
